// Global country stances on the Iran–Israel war (Feb 2026 → present)
// alignment: 'at_war' | 'pro_israel' | 'pro_palestine' | 'pro_iran' | 'neutral'
// intensity: 'full' | 'leaning' | 'mediating' | 'observer'
// Covers all UN members + Palestine (observer state)

export const COUNTRY_STANCES = [
  // ══════════════════════ DIRECTLY AT WAR ══════════════════════
  { code: 'IL', name: 'Israel', flag: '🇮🇱', alignment: 'at_war', intensity: 'full', summary: 'Active combatant — struck Iran first on Feb 28, 2026; under daily missile attack.' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', alignment: 'at_war', intensity: 'full', summary: 'Active combatant — launched Operation True Promise III; controls regional proxy network.' },
  { code: 'US', name: 'United States', flag: '🇺🇸', alignment: 'at_war', intensity: 'full', summary: 'Co-belligerent — 2 carrier groups, direct strikes on IRGC, $14B aid package to Israel.' },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧', alignment: 'at_war', intensity: 'full', summary: 'Conflict theater — Hezbollah fires daily from south; 800k+ displaced; state can\'t control militias.' },

  // ══════════════════════ PRO-ISRAEL (FULL) ══════════════════════
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', alignment: 'pro_israel', intensity: 'full', summary: 'Carrier group in Red Sea, Five Eyes intel sharing, 45 IRGC entities sanctioned.' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', alignment: 'pro_israel', intensity: 'full', summary: 'Leads EU sanctions coordination; Patriot batteries deployed to Israel.' },
  { code: 'FR', name: 'France', flag: '🇫🇷', alignment: 'pro_israel', intensity: 'full', summary: 'Charles de Gaulle carrier in E. Med; backs EU sanctions; pushes ceasefire.' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱', alignment: 'pro_israel', intensity: 'full', summary: 'Strong EU sanctions voice; humanitarian funding but firm pro-Israel line.' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹', alignment: 'pro_israel', intensity: 'full', summary: 'Consistently pro-Israel in EU votes; condemns Iranian aggression.' },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', alignment: 'pro_israel', intensity: 'full', summary: 'Most pro-Israel EU state; recognized Israel\'s right to preemptive strikes.' },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺', alignment: 'pro_israel', intensity: 'full', summary: 'Vetoed EU statements critical of Israel; strong bilateral ties.' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', alignment: 'pro_israel', intensity: 'full', summary: 'Five Eyes ally; backtracks on Palestine recognition; supports Israeli strikes.' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', alignment: 'pro_israel', intensity: 'full', summary: 'Strong US-Israel ally; F-35 & intel cooperation; sanctions IRGC leadership.' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵', alignment: 'pro_israel', intensity: 'leaning', summary: 'Neutral frame but pro-US/Israel in practice; huge oil-dependency anxiety.' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷', alignment: 'pro_israel', intensity: 'leaning', summary: 'Condemns Iran attacks; supports US posture; energy security concerns.' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬', alignment: 'pro_israel', intensity: 'leaning', summary: 'Small-state ally; condemns Iranian strikes; depends on Gulf energy.' },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼', alignment: 'pro_israel', intensity: 'leaning', summary: 'Solidarity with Israel; monitors Gulf shipping for supply chain.' },
  { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬', alignment: 'pro_israel', intensity: 'full', summary: 'Consistent UN votes backing Israel; recognizes Jerusalem as capital.' },
  { code: 'FM', name: 'Micronesia', flag: '🇫🇲', alignment: 'pro_israel', intensity: 'full', summary: 'Pro-Israel UN voting record; co-sponsored resolutions condemning Iran.' },
  { code: 'MH', name: 'Marshall Islands', flag: '🇲🇭', alignment: 'pro_israel', intensity: 'full', summary: 'Rare pro-Israel voice in Pacific; backs US security posture.' },
  { code: 'PW', name: 'Palau', flag: '🇵🇼', alignment: 'pro_israel', intensity: 'full', summary: 'Pro-Israel UN votes; US compact-state ally.' },
  { code: 'AL', name: 'Albania', flag: '🇦🇱', alignment: 'pro_israel', intensity: 'full', summary: 'Hosts anti-Iran MEK camp; vocal supporter of Israel.' },
  { code: 'XK', name: 'Kosovo', flag: '🇽🇰', alignment: 'pro_israel', intensity: 'full', summary: 'Recognized Jerusalem; joined anti-Iran coalition.' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', alignment: 'pro_iran', intensity: 'full', summary: 'Anti-US regime; hostile to Israel; aligns with Iran in UN.' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', alignment: 'pro_israel', intensity: 'full', summary: 'Moved embassy to Jerusalem; strong pro-Israel votes.' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', alignment: 'pro_israel', intensity: 'full', summary: 'Embassy in Jerusalem; pro-Israel UN alignment.' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳', alignment: 'pro_israel', intensity: 'full', summary: 'Pro-Israel votes; embassy relocated to Jerusalem.' },

  // ══════════════════════ PRO-ISRAEL (LEANING) ══════════════════════
  { code: 'IN', name: 'India', flag: '🇮🇳', alignment: 'pro_israel', intensity: 'leaning', summary: 'Strictly neutral publicly but arms-supplies Israel; 12k nationals evacuated.' },
  { code: 'GR', name: 'Greece', flag: '🇬🇷', alignment: 'pro_israel', intensity: 'leaning', summary: 'EU ally; condemns Iran; but refrains from full combat support.' },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾', alignment: 'pro_israel', intensity: 'leaning', summary: 'Close to Israel; evacuation hub for foreign nationals.' },
  { code: 'PL', name: 'Poland', flag: '🇵🇱', alignment: 'pro_israel', intensity: 'leaning', summary: 'Condemns Iran; supports EU sanctions; moderate on Palestine.' },
  { code: 'RO', name: 'Romania', flag: '🇷🇴', alignment: 'pro_israel', intensity: 'leaning', summary: 'Pro-US NATO ally; supports Israel\'s defense.' },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', alignment: 'pro_israel', intensity: 'leaning', summary: 'EU/NATO stance; condemns Iranian missile attacks.' },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷', alignment: 'pro_israel', intensity: 'leaning', summary: 'Condemns Iran; backs EU sanctions package.' },
  { code: 'SI', name: 'Slovenia', flag: '🇸🇮', alignment: 'pro_israel', intensity: 'leaning', summary: 'Balanced EU stance; supports sanctions on Iran.' },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰', alignment: 'pro_israel', intensity: 'leaning', summary: 'Pro-Israel leaning within EU framework.' },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹', alignment: 'pro_israel', intensity: 'leaning', summary: 'NATO solidarity; condemns Iranian aggression.' },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻', alignment: 'pro_israel', intensity: 'leaning', summary: 'NATO/EU line; supports Israeli self-defense.' },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪', alignment: 'pro_israel', intensity: 'leaning', summary: 'Condemns Iran; low-profile but pro-Israel leaning.' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭', alignment: 'neutral', intensity: 'mediating', summary: 'Strictly neutral; represents US interests in Iran; hosts war-crimes documentation.' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮', alignment: 'pro_israel', intensity: 'leaning', summary: 'NATO/EU; condemns Iranian attacks; humanitarian aid to Lebanon.' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪', alignment: 'pro_israel', intensity: 'leaning', summary: 'Balanced EU line; more critical of Israel but condemns Iran strikes.' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰', alignment: 'pro_israel', intensity: 'leaning', summary: 'NATO/EU; supports sanctions; naval presence in Gulf.' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴', alignment: 'pro_israel', intensity: 'leaning', summary: 'Backed Palestine recognition but condemns Iranian escalation.' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪', alignment: 'pro_israel', intensity: 'leaning', summary: 'EU sanctions support; also funds Gaza humanitarian relief.' },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Recognized Palestine; criticizes Israel but condemns Iranian strikes.' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine leaning; recognized Palestinian state; calls for ceasefire.' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', alignment: 'neutral', intensity: 'observer', summary: 'Low-profile; supports EU sanctions but avoids taking sides.' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', alignment: 'neutral', intensity: 'observer', summary: 'EU consensus; humanitarian focus; no strong stance.' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹', alignment: 'pro_palestine', intensity: 'leaning', summary: 'UNSC member pushing ceasefire; recognizes Palestine.' },

  // ══════════════════════ PRO-PALESTINE (FULL) ══════════════════════
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', alignment: 'pro_palestine', intensity: 'full', summary: 'Calls Israeli actions genocide; suspends normalization; TRY collapsed 18%.' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Publicly pro-Palestine; secretly shares intel with US; pumps oil to stabilize.' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', alignment: 'neutral', intensity: 'mediating', summary: 'Hosts ceasefire talks; channels to both sides; Al Jazeera coverage.' },
  { code: 'AE', name: 'UAE', flag: '🇦🇪', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Abraham Accords to Israel but critical since Gaza; financial haven for Gulf.' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', alignment: 'neutral', intensity: 'mediating', summary: 'Back-channel US-Iran diplomat; historically trusted intermediary.' },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼', alignment: 'pro_palestine', intensity: 'full', summary: 'Opposes Israel normalization; pro-Palestine UN votes; wary of Iran too.' },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭', alignment: 'pro_israel', intensity: 'leaning', summary: 'Hosts US 5th Fleet; Abraham Accords member; tension with Iran proxies.' },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Peace treaty with Israel but strongly pro-Palestine; mediator role.' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Suez impacted 60%; mediates ceasefire; pro-Palestine but pragmatic.' },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶', alignment: 'pro_iran', intensity: 'leaning', summary: 'Govt neutral but Shia militias (PMF) fire on US bases; Iran-aligned.' },
  { code: 'SY', name: 'Syria', flag: '🇸🇾', alignment: 'pro_iran', intensity: 'full', summary: 'Iran\'s key ally; hosts IRGC positions; target of Israeli strikes.' },
  { code: 'YE', name: 'Yemen', flag: '🇾🇪', alignment: 'pro_iran', intensity: 'full', summary: 'Houthis fire on shipping; disrupts Red Sea; Iran-aligned faction.' },
  { code: 'LY', name: 'Libya', flag: '🇱🇾', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine statements; divided govt; limited direct role.' },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳', alignment: 'pro_palestine', intensity: 'full', summary: 'Strongly pro-Palestine; condemns Israel; anti-normalization.' },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', alignment: 'pro_palestine', intensity: 'full', summary: 'Leading pro-Palestine UN voice; condemns Israel; backs Iran diplomatically.' },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Normalized with Israel but criticizes Gaza; balances ties.' },
  { code: 'MR', name: 'Mauritania', flag: '🇲🇷', alignment: 'pro_palestine', intensity: 'full', summary: 'Pro-Palestine; OIC member; no ties with Israel.' },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Normalized with Israel then reverted; pro-Palestine rhetoric.' },
  { code: 'SS', name: 'South Sudan', flag: '🇸🇸', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine UN votes; limited global role.' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', alignment: 'pro_palestine', intensity: 'full', summary: 'Hosts foreign bases; pro-Palestine votes; Red Sea chokepoint.' },
  { code: 'SO', name: 'Somalia', flag: '🇸🇴', alignment: 'pro_palestine', intensity: 'full', summary: 'Pro-Palestine; OIC; condemns Israeli actions.' },
  { code: 'KM', name: 'Comoros', flag: '🇰🇲', alignment: 'pro_palestine', intensity: 'full', summary: 'Pro-Palestine; consistent UN votes; OIC member.' },
  { code: 'ER', name: 'Eritrea', flag: '🇪🇷', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; non-aligned; limited voice.' },
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', alignment: 'pro_palestine', intensity: 'full', summary: 'Taliban-run; strongly pro-Palestine; hostile to Israel.' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', alignment: 'pro_palestine', intensity: 'full', summary: 'No Israel recognition; PKR crashed; strong pro-Palestine protests.' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', alignment: 'pro_palestine', intensity: 'full', summary: 'Pro-Palestine; no Israel ties; major protests.' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾', alignment: 'pro_palestine', intensity: 'full', summary: 'Vocal pro-Palestine; bans Israel-linked shipping; OIC leader.' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩', alignment: 'pro_palestine', intensity: 'full', summary: 'World\'s largest Muslim nation; strongly pro-Palestine; no Israel ties.' },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳', alignment: 'pro_palestine', intensity: 'full', summary: 'No Israel recognition; pro-Palestine UN votes.' },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻', alignment: 'pro_palestine', intensity: 'full', summary: 'Suspended ties with Israel; pro-Palestine stance.' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine UN votes; fuel crisis deepens with oil surge.' },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; 1k+ nationals worked in Israel; evacuation crisis.' },
  { code: 'BT', name: 'Bhutan', flag: '🇧🇹', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Limited engagement; pro-Palestine UN pattern.' },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; military regime; low profile.' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine UN pattern; many Thai workers evacuated from Israel.' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Non-aligned; pro-Palestine votes; calls for ceasefire.' },
  { code: 'KH', name: 'Cambodia', flag: '🇰🇭', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; non-aligned bloc.' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine UN pattern; limited involvement.' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Calls for ceasefire; evacuated 15k nationals; balances ties.' },
  { code: 'TL', name: 'Timor-Leste', flag: '🇹🇱', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; small OIC-adjacent voice.' },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Non-aligned; pro-Palestine UN pattern.' },

  // ══════════════════════ PRO-IRAN / ANTI-WEST AXIS ══════════════════════
  { code: 'RU', name: 'Russia', flag: '🇷🇺', alignment: 'pro_iran', intensity: 'full', summary: 'Vetoes Israel-critical UNSC votes; supplies Iran S-400 parts; benefits from oil surge.' },
  { code: 'CN', name: 'China', flag: '🇨🇳', alignment: 'pro_iran', intensity: 'full', summary: 'Calls for ceasefire but vetoes US resolutions; buys discounted Iranian oil.' },
  { code: 'KP', name: 'North Korea', flag: '🇰🇵', alignment: 'pro_iran', intensity: 'full', summary: 'Aligned with Iran; shares missile tech; hostile to US/Israel.' },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾', alignment: 'pro_iran', intensity: 'full', summary: 'Russia-aligned; supports Iran in UN; hostile to West.' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', alignment: 'pro_iran', intensity: 'full', summary: 'Anti-US; allies with Iran; condemns Israel.' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', alignment: 'pro_iran', intensity: 'full', summary: 'Deep Iran ties; oil cooperation; anti-US rhetoric.' },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴', alignment: 'pro_iran', intensity: 'leaning', summary: 'Severed Israel ties; pro-Palestine; Iran-friendly.' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', alignment: 'pro_iran', intensity: 'leaning', summary: 'Anti-Western; pro-Palestine; limited Iran ties.' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱', alignment: 'pro_iran', intensity: 'leaning', summary: 'Junta regime; pro-Palestine; anti-French/Western.' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', alignment: 'pro_iran', intensity: 'leaning', summary: 'Junta regime; pro-Palestine; Russia-friendly.' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪', alignment: 'pro_iran', intensity: 'leaning', summary: 'Junta; pro-Palestine; expelled Western forces.' },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫', alignment: 'pro_iran', intensity: 'leaning', summary: 'Russia/Wagner influence; pro-Palestine votes.' },
  { code: 'TD', name: 'Chad', flag: '🇹🇩', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; limited global role.' },
  { code: 'CG', name: 'Congo (Republic)', flag: '🇨🇬', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine UN votes; Africa bloc.' },
  { code: 'CD', name: 'DR Congo', flag: '🇨🇩', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; large UN cohort.' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; African bloc.' },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; calls for ceasefire.' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine but balanced; oil exporter; Africa\'s largest economy.' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; moderate OIC observer.' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳', alignment: 'pro_palestine', intensity: 'full', summary: 'OIC chair history; strongly pro-Palestine.' },
  { code: 'CI', name: 'Côte d\'Ivoire', flag: '🇨🇮', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; African bloc.' },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine UN pattern.' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; African bloc.' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; OIC member.' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; limited role.' },
  { code: 'GN', name: 'Guinea', flag: '🇬🇳', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; OIC member.' },
  { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; OIC member.' },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine; OIC member.' },
  { code: 'CV', name: 'Cape Verde', flag: '🇨🇻', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; African bloc.' },
  { code: 'ST', name: 'São Tomé and Príncipe', flag: '🇸🇹', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine UN pattern.' },
  { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; oil exporter.' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; oil economy impacted.' },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; African bloc.' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; fuel crisis from war.' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; LNG exporter impacted.' },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦', alignment: 'pro_palestine', intensity: 'full', summary: 'Outspokenly pro-Palestine; condemns Israel.' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; African bloc.' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes.' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; limited role.' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; African bloc.' },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; island economy.' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; tourism impacted.' },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; strong UN presence.' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; UNSC member; diplomatic hub.' },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; non-aligned.' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; African bloc.' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; UNSC seat.' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes.' },

  // ══════════════════════ NEUTRAL / OBSERVER ══════════════════════
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', alignment: 'neutral', intensity: 'observer', summary: 'Balanced; sells oil to both sides; hosts peace talks.' },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', alignment: 'neutral', intensity: 'observer', summary: 'Neutral; focuses on trade; no strong stance.' },
  { code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬', alignment: 'neutral', intensity: 'observer', summary: 'Neutral; Russia-leaning but non-aligned on war.' },
  { code: 'TJ', name: 'Tajikistan', flag: '🇹🇯', alignment: 'neutral', intensity: 'observer', summary: 'Neutral; limited involvement.' },
  { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲', alignment: 'neutral', intensity: 'observer', summary: 'Permanently neutral; sells gas to all.' },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲', alignment: 'neutral', intensity: 'observer', summary: 'Neutral; Russia-allied but no war stance.' },
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', alignment: 'neutral', intensity: 'observer', summary: 'Sells oil to Israel & Europe; discreet balance.' },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪', alignment: 'neutral', intensity: 'observer', summary: 'Neutral; transit corridor; no direct stance.' },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩', alignment: 'neutral', intensity: 'observer', summary: 'EU-leaning but non-committal on the war.' },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸', alignment: 'neutral', intensity: 'observer', summary: 'Balances EU & Russia; no firm stance.' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', alignment: 'neutral', intensity: 'observer', summary: 'Internal divisions; pro-Palestine leaning in votes.' },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪', alignment: 'neutral', intensity: 'observer', summary: 'NATO/EU accession; cautious neutrality.' },
  { code: 'MK', name: 'North Macedonia', flag: '🇲🇰', alignment: 'neutral', intensity: 'observer', summary: 'NATO member; low-key stance.' },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨', alignment: 'neutral', intensity: 'observer', summary: 'Neutral microstate; no stance.' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', alignment: 'neutral', intensity: 'observer', summary: 'Neutral microstate.' },
  { code: 'AD', name: 'Andorra', flag: '🇦🇩', alignment: 'neutral', intensity: 'observer', summary: 'Neutral microstate.' },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲', alignment: 'neutral', intensity: 'observer', summary: 'Neutral microstate.' },
  { code: 'VA', name: 'Holy See (Vatican)', flag: '🇻🇦', alignment: 'neutral', intensity: 'mediating', summary: 'Calls for ceasefire; humanitarian diplomacy; neutral.' },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸', alignment: 'neutral', intensity: 'observer', summary: 'NATO but no army; humanitarian focus.' },
  { code: 'JE', name: 'Jersey', flag: '🇯🇪', alignment: 'neutral', intensity: 'observer', summary: 'Crown dependency; no stance.' },

  // ══════════════════════ LATIN AMERICA ══════════════════════
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Calls for ceasefire; Lula critical of Israel; condemns Iranian strikes.' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Evacuated citizens; calls for ceasefire; pro-Palestine leaning.' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', alignment: 'pro_israel', intensity: 'leaning', summary: 'Milei strongly pro-Israel; but economic strain limits action.' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine; recalled ambassador from Israel.' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', alignment: 'pro_palestine', intensity: 'full', summary: 'Petro severed ties with Israel; strongly pro-Palestine.' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine UN votes; calls for ceasefire.' },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; moderate.' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', alignment: 'neutral', intensity: 'observer', summary: 'Balanced; humanitarian calls; no strong stance.' },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; Caribbean bloc.' },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; Caribbean bloc.' },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; CARICOM.' },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; CARICOM.' },
  { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; CARICOM.' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; CARICOM.' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; CARICOM.' },
  { code: 'HT', name: 'Haiti', flag: '🇭🇹', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; crisis-ridden state.' },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; moderate.' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', alignment: 'neutral', intensity: 'observer', summary: 'Historic pro-Israel tilt but calls for ceasefire.' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', alignment: 'pro_israel', intensity: 'leaning', summary: 'Canal impact; pro-Israel leaning.' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻', alignment: 'pro_israel', intensity: 'leaning', summary: 'Moved embassy to Jerusalem; pro-Israel.' },
  { code: 'GD', name: 'Grenada', flag: '🇬🇩', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; CARICOM.' },
  { code: 'VC', name: 'Saint Vincent', flag: '🇻🇨', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; CARICOM.' },
  { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; CARICOM.' },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; CARICOM.' },
  { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; CARICOM.' },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; CARICOM.' },

  // ══════════════════════ PACIFIC / OTHER ══════════════════════
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯', alignment: 'neutral', intensity: 'observer', summary: 'Neutral; peacekeeping tradition; no stance.' },
  { code: 'SB', name: 'Solomon Islands', flag: '🇸🇧', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes; China-influenced.' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes.' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes.' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴', alignment: 'neutral', intensity: 'observer', summary: 'Neutral; no stance.' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Pro-Palestine votes.' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷', alignment: 'pro_israel', intensity: 'full', summary: 'Pro-Israel votes; US-aligned.' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻', alignment: 'neutral', intensity: 'observer', summary: 'Neutral microstate.' },

  // ══════════════════════ ADDITIONAL MEMBERS & OBSERVER STATES ══════════════════════
  { code: 'IT', name: 'Italy', flag: '🇮🇹', alignment: 'pro_israel', intensity: 'full', summary: 'EU/NATO core; naval presence in Red Sea; strong sanctions line on Iran.' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', alignment: 'pro_palestine', intensity: 'leaning', summary: 'Calls for ceasefire; recognizes Palestinian state; condemns Iranian strikes.' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', alignment: 'pro_israel', intensity: 'leaning', summary: 'Victim of Iranian drones; pro-Western; backs Israel\'s right to defend.' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', alignment: 'pro_palestine', intensity: 'full', summary: 'Filed ICJ genocide case vs Israel; OIC-aligned; leads anti-Israel bloc.' },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸', alignment: 'pro_palestine', intensity: 'full', summary: 'Conflict party — statehood recognition drive; UN observer member.' },
  { code: 'EH', name: 'Western Sahara', flag: '🇪🇭', alignment: 'pro_palestine', intensity: 'leaning', summary: 'SADR OIC observer; pro-Palestine in UN votes.' },

  // ══════════════════════ TERRITORIES / DEPENDENCIES (neutral) ══════════════════════
  { code: 'PR', name: 'Puerto Rico', flag: '🇵🇷', alignment: 'neutral', intensity: 'observer', summary: 'US territory — follows US stance; no independent vote.' },
  { code: 'GL', name: 'Greenland', flag: '🇬🇱', alignment: 'neutral', intensity: 'observer', summary: 'Danish territory; no independent war stance.' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰', alignment: 'neutral', intensity: 'observer', summary: 'China SAR — follows Beijing; no independent stance.' },
  { code: 'MO', name: 'Macau', flag: '🇲🇴', alignment: 'neutral', intensity: 'observer', summary: 'China SAR — follows Beijing; no independent stance.' },
  { code: 'GI', name: 'Gibraltar', flag: '🇬🇮', alignment: 'neutral', intensity: 'observer', summary: 'UK territory; no independent stance.' },
  { code: 'GG', name: 'Guernsey', flag: '🇬🇬', alignment: 'neutral', intensity: 'observer', summary: 'Crown dependency; no independent stance.' },
  { code: 'IM', name: 'Isle of Man', flag: '🇮🇲', alignment: 'neutral', intensity: 'observer', summary: 'Crown dependency; no independent stance.' },
  { code: 'FO', name: 'Faroe Islands', flag: '🇫🇴', alignment: 'neutral', intensity: 'observer', summary: 'Danish territory; no independent stance.' },
  { code: 'AX', name: 'Aland Islands', flag: '🇦🇽', alignment: 'neutral', intensity: 'observer', summary: 'Finnish autonomous territory; no stance.' },
  { code: 'SJ', name: 'Svalbard & Jan Mayen', flag: '🇸🇯', alignment: 'neutral', intensity: 'observer', summary: 'Norwegian territory; no stance.' },
  { code: 'BM', name: 'Bermuda', flag: '🇧🇲', alignment: 'neutral', intensity: 'observer', summary: 'UK territory; no independent stance.' },
  { code: 'KY', name: 'Cayman Islands', flag: '🇰🇾', alignment: 'neutral', intensity: 'observer', summary: 'UK territory; financial hub; no stance.' },
  { code: 'VG', name: 'British Virgin Islands', flag: '🇻🇬', alignment: 'neutral', intensity: 'observer', summary: 'UK territory; no independent stance.' },
  { code: 'VI', name: 'US Virgin Islands', flag: '🇻🇮', alignment: 'neutral', intensity: 'observer', summary: 'US territory; follows US stance.' },
  { code: 'GU', name: 'Guam', flag: '🇬🇺', alignment: 'neutral', intensity: 'observer', summary: 'US territory — key Pacific military base; no independent vote.' },
  { code: 'AS', name: 'American Samoa', flag: '🇦🇸', alignment: 'neutral', intensity: 'observer', summary: 'US territory; no independent stance.' },
  { code: 'MP', name: 'Northern Mariana Islands', flag: '🇲🇵', alignment: 'neutral', intensity: 'observer', summary: 'US territory; no independent stance.' },
  { code: 'AW', name: 'Aruba', flag: '🇦🇼', alignment: 'neutral', intensity: 'observer', summary: 'Dutch territory; no independent stance.' },
  { code: 'CW', name: 'Curaçao', flag: '🇨🇼', alignment: 'neutral', intensity: 'observer', summary: 'Dutch territory; no independent stance.' },
  { code: 'SX', name: 'Sint Maarten', flag: '🇸🇽', alignment: 'neutral', intensity: 'observer', summary: 'Dutch territory; no independent stance.' },
  { code: 'BQ', name: 'Caribbean Netherlands', flag: '🇧🇶', alignment: 'neutral', intensity: 'observer', summary: 'Dutch special municipalities; no stance.' },
  { code: 'GF', name: 'French Guiana', flag: '🇬🇫', alignment: 'neutral', intensity: 'observer', summary: 'French overseas dept; follows France.' },
  { code: 'GP', name: 'Guadeloupe', flag: '🇬🇵', alignment: 'neutral', intensity: 'observer', summary: 'French overseas dept; follows France.' },
  { code: 'MQ', name: 'Martinique', flag: '🇲🇶', alignment: 'neutral', intensity: 'observer', summary: 'French overseas dept; follows France.' },
  { code: 'RE', name: 'Réunion', flag: '🇷🇪', alignment: 'neutral', intensity: 'observer', summary: 'French overseas dept; follows France.' },
  { code: 'YT', name: 'Mayotte', flag: '🇾🇹', alignment: 'neutral', intensity: 'observer', summary: 'French overseas dept; follows France.' },
  { code: 'NC', name: 'New Caledonia', flag: '🇳🇨', alignment: 'neutral', intensity: 'observer', summary: 'French territory; no independent stance.' },
  { code: 'PF', name: 'French Polynesia', flag: '🇵🇫', alignment: 'neutral', intensity: 'observer', summary: 'French territory; no independent stance.' },
  { code: 'WF', name: 'Wallis and Futuna', flag: '🇼🇫', alignment: 'neutral', intensity: 'observer', summary: 'French territory; no independent stance.' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', flag: '🇵🇲', alignment: 'neutral', intensity: 'observer', summary: 'French territory; no independent stance.' },
  { code: 'BL', name: 'Saint Barthélemy', flag: '🇧🇱', alignment: 'neutral', intensity: 'observer', summary: 'French territory; no independent stance.' },
  { code: 'MF', name: 'Saint Martin', flag: '🇲🇫', alignment: 'neutral', intensity: 'observer', summary: 'French territory; no independent stance.' },
  { code: 'CK', name: 'Cook Islands', flag: '🇨🇰', alignment: 'neutral', intensity: 'observer', summary: 'NZ-associated state; no independent stance.' },
  { code: 'NU', name: 'Niue', flag: '🇳🇺', alignment: 'neutral', intensity: 'observer', summary: 'NZ-associated state; no independent stance.' },
  { code: 'TK', name: 'Tokelau', flag: '🇹🇰', alignment: 'neutral', intensity: 'observer', summary: 'NZ territory; no independent stance.' },
  { code: 'FK', name: 'Falkland Islands', flag: '🇫🇰', alignment: 'neutral', intensity: 'observer', summary: 'UK territory; no independent stance.' },
  { code: 'TC', name: 'Turks and Caicos', flag: '🇹🇨', alignment: 'neutral', intensity: 'observer', summary: 'UK territory; no independent stance.' },
  { code: 'AI', name: 'Anguilla', flag: '🇦🇮', alignment: 'neutral', intensity: 'observer', summary: 'UK territory; no independent stance.' },
  { code: 'MS', name: 'Montserrat', flag: '🇲🇸', alignment: 'neutral', intensity: 'observer', summary: 'UK territory; no independent stance.' },
  { code: 'SH', name: 'Saint Helena', flag: '🇸🇭', alignment: 'neutral', intensity: 'observer', summary: 'UK territory; no independent stance.' },
  { code: 'GS', name: 'South Georgia', flag: '🇬🇸', alignment: 'neutral', intensity: 'observer', summary: 'UK territory; uninhabited.' },
  { code: 'IO', name: 'British Indian Ocean', flag: '🇮🇴', alignment: 'neutral', intensity: 'observer', summary: 'UK territory; Diego Garcia base.' },
  { code: 'PN', name: 'Pitcairn Islands', flag: '🇵🇳', alignment: 'neutral', intensity: 'observer', summary: 'UK territory; no stance.' },
  { code: 'BV', name: 'Bouvet Island', flag: '🇧🇻', alignment: 'neutral', intensity: 'observer', summary: 'Norwegian uninhabited territory.' },
  { code: 'HM', name: 'Heard Island', flag: '🇭🇲', alignment: 'neutral', intensity: 'observer', summary: 'Australian uninhabited territory.' },
  { code: 'CC', name: 'Cocos Islands', flag: '🇨🇨', alignment: 'neutral', intensity: 'observer', summary: 'Australian territory; no stance.' },
  { code: 'CX', name: 'Christmas Island', flag: '🇨🇽', alignment: 'neutral', intensity: 'observer', summary: 'Australian territory; no stance.' },
  { code: 'NF', name: 'Norfolk Island', flag: '🇳🇫', alignment: 'neutral', intensity: 'observer', summary: 'Australian territory; no stance.' },
  { code: 'TF', name: 'French Southern Lands', flag: '🇹🇫', alignment: 'neutral', intensity: 'observer', summary: 'French uninhabited territory.' },
  { code: 'GO', name: 'Glorioso Islands', flag: '🇬🇴', alignment: 'neutral', intensity: 'observer', summary: 'French uninhabited territory.' },
  { code: 'JU', name: 'Juan de Nova Island', flag: '🇯🇺', alignment: 'neutral', intensity: 'observer', summary: 'French uninhabited territory.' },
  { code: 'UM', name: 'US Minor Outlying Islands', flag: '🇺🇲', alignment: 'neutral', intensity: 'observer', summary: 'US uninhabited territories.' },
]

// Alignment metadata for display + map coloring (muted, on-theme tints)
export const ALIGNMENT_META = {
  at_war: { label: 'Directly At War', color: '#B85C5C', bg: '#FBEFEF' },
  pro_israel: { label: 'Pro-Israel / US Coalition', color: '#5B7EA6', bg: '#EFF4F8' },
  pro_palestine: { label: 'Pro-Palestine', color: '#C9935A', bg: '#FBF4EA' },
  pro_iran: { label: 'Pro-Iran / Axis', color: '#8A74B8', bg: '#F2EFF8' },
  neutral: { label: 'Neutral / Mediating', color: '#2D9E5F', bg: '#E8F5EE' },
}

export const INTENSITY_META = {
  full: { label: 'Full', color: '#DC2626' },
  leaning: { label: 'Leaning', color: '#D97706' },
  mediating: { label: 'Mediating', color: '#1D4ED8' },
  observer: { label: 'Observer', color: '#6B7280' },
}

// Dedupe by code (there were duplicate shorthand entries above)
export function getUniqueCountryStances() {
  const seen = new Set()
  const unique = []
  for (const c of COUNTRY_STANCES) {
    const key = c.code.slice(0, 2).toUpperCase()
    if (seen.has(key)) continue
    seen.add(key)
    unique.push({ ...c, code: key })
  }
  return unique
}

export function getAlignmentGroups() {
  const countries = getUniqueCountryStances()
  const groups = {
    at_war: [],
    pro_israel: [],
    pro_palestine: [],
    pro_iran: [],
    neutral: [],
  }
  for (const c of countries) {
    groups[c.alignment].push(c)
  }
  return groups
}

// Map ISO codes → profile for the world map
export function getStanceLookup() {
  const map = {}
  for (const c of getUniqueCountryStances()) {
    map[c.code.toLowerCase()] = c
  }
  return map
}